name: "Push build information to Octopus"
on: [push]
env:
  OCTOPUS_HOST: ${{ secrets.OCTOPUS_URL }}
  OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_API_KEY }}
jobs:
  push-build-information:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run
        run: echo "hello ${{ github.event.head_commit.author.username }}"
        if: ${{ github.event.head_commit.author.username != 'alfhenrik-test-2' }}
      - name: alt run
        run: echo "hello release-please change"
        if: ${{ github.event.head_commit.author.username == 'alfhenrik-test-2' }}
