name: test-octopus-upload 
run-name: ${{ github.actor }} running octopus package upload 
on: 
  workflow_dispatch:
    inputs:
      package_id:
        default: "ion-backend-legacy"
        required: true
        type: string
      package_version:
        default: "3.27.0-dev-master-6481-bcg6571"
        required: true
        type: string
permissions:
  id-token: write
env:
  OCTOPUS_SPACE: Default
jobs: 
  test-octopus-upload: 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v5 
      - uses: actions/setup-node@v4 
      - run: fallocate -l 214748300 "${{ inputs.package_id }}.${{ inputs.package_version }}-${{ github.run_number }}.zip" 
      
      - name: Install Octopus CLI 
        uses: OctopusDeploy/install-octopus-cli-action@v4 
        with: 
          version: 

      - name: Login to Octopus Deploy 
        uses: OctopusDeploy/login@v1
        with: 
          server: ${{secrets.OctopusServer}}
          service_account_id: b596f88f-562e-43eb-8d78-707c6726ef16 #48ac31f4-2574-4190-8ced-a925f589cbf1
    
      - name: Push a package to Octopus Deploy
        uses: OctopusDeploy/push-package-action@v4
        with:
          packages: |
            ${{ inputs.package_id }}.${{ inputs.package_version }}-${{ github.run_number }}.zip
          overwrite_mode: IgnoreIfExists
